export const alerts = [
  "La curiosidad mató al gato",
  "¿Sabías que nací en Estados Unidos?",
  "Si apretas otra vez tendrás otro dato.",
  "El elefante es el único animal que no puede saltar.",
  "¿Sabías que las vacas tienen mejores amigas?",
  "El café fue descubierto por un pastor de cabras en Etiopía.",
  "¿Sabías que el ajedrez se inventó en la India?",
  "El oro es comestible y se utiliza en la gastronomía de lujo.",
  "¿Sabías que los pingüinos tienen una sola pareja para toda la vida?",
  "Si estornudas con los ojos abiertos, ¡se pueden salir!",
  "¿Sabías que las abejas pueden reconocer rostros humanos?",
  "La risa es contagiosa, incluso si no sabes por qué te ríes.",
  "¿Sabías que las personas somos más altas en la mañana que en la noche?",
  "El hipo es el resultado de un espasmo del diafragma.",
  "¿Sabías que hay más estrellas en el universo que granos de arena en todas las playas del mundo?",
  "El pelo y las uñas siguen creciendo después de la muerte.",
  "¿Sabías que los pulpos tienen tres corazones?",
  "El sonido del trueno es causado por el calor del rayo.",
  "¿Sabías que el ojo humano puede distinguir hasta 10 millones de colores?",
  "El chocolate fue utilizado como moneda en la antigua civilización azteca.",
  "¿Sabías que los osos polares son zurdos?",
  "El aguacate es una fruta y no un vegetal.",
  "¿Sabías que los perros tienen huellas digitales?",
  "Las hormigas no duermen.",
  "¿Sabías que los lobos aúllan para comunicarse con su manada?",
  "Las cebras tienen rayas únicas, al igual que las huellas dactilares en los humanos.",
  "¿Sabías que las jirafas tienen el mismo número de huesos en el cuello que los humanos?",
  "El kiwi es originario de China y se le llamaba originalmente 'grosella china'.",
  "¿Sabías que el tiburón ballena es el pez más grande del mundo?",
  "Los pingüinos no tienen miedo de nadar junto a los tiburones.",
  "¿Sabías que los gatos tienen 32 músculos en cada oreja?",
];
